#not use
---
index: marchebe
body:
  settings:
    number_of_shards: 2
    number_of_replicas: 0
    analysis:
      filter:
        french_elision:
          type: elision
          articles_case: true
          articles:
            - l
            - m
            - t
            - qu
            - n
            - s
            - j
            - d
            - c
            - jusqu
            - quoiqu
            - lorsqu
            - puisqu
        french_synonym:
          type: synonym
          ignore_case: true
          expand: true
          synonyms:
            - salade, laitue
            - mayo, mayonnaise
            - grille, toaste
        french_stemmer:
          type: stemmer
          language: light_french
      analyzer:
        french_heavy:
          tokenizer: icu_tokenizer
          filter:
            - french_elision
            - icu_folding
            - french_synonym
            - french_stemmer
        french_light:
          tokenizer: icu_tokenizer
          filter:
            - french_elision
            - icu_folding
  mappings:
    properties:
      type:
        type: keyword
      blog:
        type: text
        index: 'false'
      date:
        type: date
        format: strict_date_optional_time||epoch_millis
      guid:
        type: text
        index: 'false'
      permalink:
        type: text
        index: 'false'
      post_ID:
        type: long
        index: 'false'
      post_content:
        type: text
        analyzer: french_light
        fields:
          stemmed:
            type: text
            analyzer: french_heavy
      post_date:
        type: date
        format: strict_date_optional_time||epoch_millis
      post_excerpt:
        type: text
        analyzer: french_light
        fields:
          stemmed:
            type: text
            analyzer: french_heavy
      post_name:
        type: text
        index: 'false'
      post_title:
        type: text
        analyzer: french_light
        boost: 2
        fields:
          stemmed:
            type: text
            analyzer: french_heavy
      post_suggest:
        type: completion
        analyzer: standard
        search_analyzer: simple
      post_autocomplete:
        type: text
        analyzer: standard
        search_analyzer: standard
      categories:
        properties:
          cat_name:
            type: text
            analyzer: french
          cat_name_autocomplete:
            type: text
            analyzer: standard
            search_analyzer: standard
          cat_description:
            type: text
            analyzer: french_light
            fields:
              stemmed:
                type: text
                analyzer: french_heavy
      post_mime_type:
        type: text
      post_status:
        type: text
